# Generated by Django 2.1.5 on 2020-09-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='feed',
            name='image',
            field=models.ImageField(upload_to='timeline'),
        ),
    ]
